### ISSUE TITLE
Vue package version mismatch

### ISSUE THREAD

**Issue by Dade3007** [nono1526/vue-material-year-calendar#30]
I have the following error when I try to use the component.

> ERROR in ./node_modules/vue-material-year-calendar/src/components/YearCalendar.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.5.22 (/home/dade/projects/faro-security/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/home/dade/projects/faro-security/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/home/dade/projects/faro-security/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dade/projects/faro-security/node_modules/vue-loader/lib/parser.js:1:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dade/projects/faro-security/node_modules/vue-loader/lib/loader.js:3:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dade/projects/faro-security/node_modules/vue-loader/index.js:1:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
 @ ./node_modules/vue-material-year-calendar/index.js 1:0-60
 @ ./webapp/src/components/turns/holidays/holidays.ts
 @ ./webapp/src/components/turns/holidays/index.ts
 @ ./webapp/src/router.ts
 @ ./webapp/src/main.ts

Tried to update vue-template-compiler as suggested but doesnt work....

**Comment by nono1526** [comment]
Use vue-template-compiler@2.5.22 will work fine.
