### ISSUE TITLE
在vue3+ts项目中使用报错

### ISSUE THREAD

**Issue by Sunery0408** [nono1526/vue-material-year-calendar#53]
SyntaxError: The requested module '/node_modules/dayjs/dayjs.min.js?v=1b2b26ec' does not provide an export named 'dayjs' (at MonthCalendar.vue:23:9)

**Comment by lugela988** [comment]
> SyntaxError: The requested module '/node_modules/dayjs/dayjs.min.js?v=1b2b26ec' does not provide an export named 'dayjs' (at MonthCalendar.vue:23:9)

请问解决了吗

**Comment by Sunery0408** [comment]
我也忘了
